# This pipeline uses output files generated by the "qc_and_filtering.ipynb" notebook
# and assumes that adata.X in the input .h5ad files
# contains RAW (unnormalized) counts.
# If adata.X is normalized or log-transformed, set RAW_USE = FALSE.


suppressPackageStartupMessages({
  library(CellChat)
  library(zellkonverter)
  library(SingleCellExperiment)
  library(SummarizedExperiment)
  library(Matrix)
  library(data.table)
  library(glue)
})

set.seed(123)
options(stringsAsFactors = FALSE)

# ============================================================
# Global parameters
# ============================================================

# ---- INPUT FILES (from Python pipeline) ----
INPUT_FILES <- list(
  N = "GSE178341_normal.h5ad",
  T = "GSE178341_tumor.h5ad"
)

# ---- METADATA COLUMNS  ----
OBS_PATIENT_COL <- "Patient_ID"
OBS_LABEL_COL   <- "clMidwayPr"     # or "clTopLevel"

# ---- OUTPUT ----
OUT_ROOT <- "cellchat"

# ---- CELLCHAT SETTINGS ----
MIN_CELLS_PER_GROUP <- 20
NBOOT               <- 50   
RAW_USE             <- TRUE

# ---- CellChat database ----
DB_PATH <- "/Users/aleksandrmilek/myDB_CellChat_human_with_RSPO.rds"
cellchat_db <- readRDS(DB_PATH)

# NOTE: This is a custom-modified CellChat human database.
# RSPO–LGR interactions (RSPO1-4 - LGR4-6) were manually added
# to capture WNT/RSPO signaling relevant for organoid culture systems.

# ============================================================
# Helper functions
# ============================================================

message("Reading AnnData via zellkonverter...")

.read_h5ad_counts <- function(path) {
  sce <- zellkonverter::readH5AD(path)

  assay_names <- SummarizedExperiment::assayNames(sce)
  message("Assays available: ", paste(assay_names, collapse = ", "))

  # ---- choose assay ----
  assay_use <- if ("counts" %in% assay_names) {
    "counts"
  } else if ("X" %in% assay_names) {
    "X"
  } else {
    stop(
      "No suitable assay found in h5ad. Available: ",
      paste(assay_names, collapse = ", "),
      " | file: ", path
    )
  }

  message("Using assay: ", assay_use)

  mat <- SummarizedExperiment::assay(sce, assay_use)
  meta <- as.data.frame(SummarizedExperiment::colData(sce))

  # ---- orientation check ----
  if (ncol(mat) != nrow(meta) && nrow(mat) == nrow(meta)) {
    mat <- Matrix::t(mat)
  }

  if (ncol(mat) != nrow(meta)) {
    stop(
      "Matrix/metadata mismatch: dim(mat)=",
      paste(dim(mat), collapse = "x"),
      " | nrow(meta)=",
      nrow(meta)
    )
  }

  # ---- ensure dgCMatrix ----
  if (!inherits(mat, "dgCMatrix")) {
    mat <- as(mat, "dgCMatrix")
  }

  list(
    mat = mat,
    meta = meta,
    assay_used = assay_use
  )
}


.run_cellchat_for_patient <- function(mat, meta, patient_id, condition) {

  idx <- which(meta[[OBS_PATIENT_COL]] == patient_id)
  if (length(idx) == 0) return(NULL)

  mat_p <- mat[, idx, drop = FALSE]
  meta_p <- meta[idx, , drop = FALSE]

  labels <- as.character(meta_p[[OBS_LABEL_COL]])
  names(labels) <- colnames(mat_p)

  # drop NA / empty labels
  keep <- !is.na(labels) & nzchar(labels)
  mat_p <- mat_p[, keep, drop = FALSE]
  labels <- labels[keep]

  # collapse small groups
  tab <- table(labels)
  small <- names(tab)[tab < MIN_CELLS_PER_GROUP]
  if (length(small) > 0) {
    labels[labels %in% small] <- "Other"
  }

  meta_cc <- data.frame(
    labels = factor(labels),
    row.names = colnames(mat_p)
  )

  # remove zero genes 
  mat_p <- mat_p[rowSums(mat_p) > 0, , drop = FALSE]

  cellchat <- createCellChat(
    object   = mat_p,
    meta     = meta_cc,
    group.by = "labels"
  )

  cellchat@DB <- cellchat_db
  cellchat <- subsetData(cellchat)

  if (nrow(cellchat@data.signaling) == 0) {
    message(glue("  [{condition} | {patient_id}] No signaling genes — skipped"))
    return(NULL)
  }

  cellchat <- identifyOverExpressedGenes(cellchat)
  cellchat <- identifyOverExpressedInteractions(cellchat)

  cellchat <- computeCommunProb(
    cellchat,
    raw.use        = RAW_USE,
    population.size = TRUE,
    type           = "truncatedMean",
    nboot          = NBOOT
  )

  cellchat <- filterCommunication(
    cellchat,
    min.cells = MIN_CELLS_PER_GROUP
  )

  cellchat <- computeCommunProbPathway(cellchat)
  cellchat <- aggregateNet(cellchat)

  # ---- SAVE ----
  out_dir <- file.path(OUT_ROOT, condition, paste0("Patient_", patient_id))
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  saveRDS(
    cellchat,
    file = file.path(out_dir, glue("cellchat_{condition}_{patient_id}.rds"))
  )

  df_comm <- subsetCommunication(cellchat)
  fwrite(
    df_comm,
    file = file.path(out_dir, glue("cellchat_interactions_{condition}_{patient_id}.tsv")),
    sep = "\t"
  )

  message(glue(
    "  [{condition} | {patient_id}] ",
    nrow(df_comm), " interactions saved"
  ))
}

# ============================================================
# MAIN LOOP
# ============================================================

for (cond in names(INPUT_FILES)) {

  message(glue("\n=== CONDITION: {cond} ==="))

  inp <- .read_h5ad_counts(INPUT_FILES[[cond]])
  mat  <- inp$mat
  meta <- inp$meta

  stopifnot(
    OBS_PATIENT_COL %in% colnames(meta),
    OBS_LABEL_COL   %in% colnames(meta)
  )

  patients <- sort(unique(meta[[OBS_PATIENT_COL]]))

  message(glue("Found {length(patients)} patients"))

  for (pt in patients) {
    message(glue("Processing patient: {pt}"))
    .run_cellchat_for_patient(mat, meta, pt, cond)
  }
}

message("\n== CellChat calculation completed ==")
